name: Static type checks (Pyright)

on: [push, pull_request]

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jakebailey/pyright-action@v1
        with:
          version: 1.1.295
